// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sharding/protobuf.proto

/*
Package sharding is a generated protocol buffer package.

It is generated from these files:
	sharding/protobuf.proto

It has these top-level messages:
	AssociatedData
	ProtoShard
*/
package sharding

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AssociatedData struct {
	Uuid      []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Threshold int32  `protobuf:"varint,2,opt,name=threshold" json:"threshold,omitempty"`
	Shares    int32  `protobuf:"varint,3,opt,name=shares" json:"shares,omitempty"`
}

func (m *AssociatedData) Reset()                    { *m = AssociatedData{} }
func (m *AssociatedData) String() string            { return proto.CompactTextString(m) }
func (*AssociatedData) ProtoMessage()               {}
func (*AssociatedData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AssociatedData) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *AssociatedData) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *AssociatedData) GetShares() int32 {
	if m != nil {
		return m.Shares
	}
	return 0
}

type ProtoShard struct {
	Associated *AssociatedData `protobuf:"bytes,1,opt,name=associated" json:"associated,omitempty"`
	Index      int32           `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Keyshare   []byte          `protobuf:"bytes,3,opt,name=keyshare,proto3" json:"keyshare,omitempty"`
	Pubkey     []byte          `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Signature  []byte          `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Data       []byte          `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ProtoShard) Reset()                    { *m = ProtoShard{} }
func (m *ProtoShard) String() string            { return proto.CompactTextString(m) }
func (*ProtoShard) ProtoMessage()               {}
func (*ProtoShard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoShard) GetAssociated() *AssociatedData {
	if m != nil {
		return m.Associated
	}
	return nil
}

func (m *ProtoShard) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ProtoShard) GetKeyshare() []byte {
	if m != nil {
		return m.Keyshare
	}
	return nil
}

func (m *ProtoShard) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *ProtoShard) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ProtoShard) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AssociatedData)(nil), "sharding.AssociatedData")
	proto.RegisterType((*ProtoShard)(nil), "sharding.ProtoShard")
}

func init() { proto.RegisterFile("sharding/protobuf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4a, 0x04, 0x31,
	0x10, 0x84, 0x89, 0xee, 0x0c, 0x6b, 0xbb, 0x78, 0x68, 0x44, 0x83, 0x78, 0x58, 0xf6, 0xb4, 0xa7,
	0x11, 0xf4, 0xe2, 0x55, 0xf0, 0x01, 0x24, 0xde, 0xbc, 0xf5, 0x98, 0xb8, 0x13, 0x56, 0x26, 0x43,
	0x7e, 0xc0, 0x79, 0x3d, 0x9f, 0x4c, 0xd2, 0xf3, 0xe7, 0xde, 0xba, 0xba, 0x42, 0x7f, 0x55, 0x81,
	0xdb, 0xd0, 0x90, 0xd7, 0xb6, 0x3d, 0x3c, 0x74, 0xde, 0x45, 0x57, 0xa7, 0xaf, 0x8a, 0x07, 0x5c,
	0x4f, 0xc6, 0xee, 0x03, 0xae, 0x5e, 0x42, 0x70, 0x9f, 0x96, 0xa2, 0xd1, 0xaf, 0x14, 0x09, 0x11,
	0x56, 0x29, 0x59, 0x2d, 0xc5, 0x56, 0xec, 0x37, 0x8a, 0x67, 0xbc, 0x87, 0x8b, 0xd8, 0x78, 0x13,
	0x1a, 0xf7, 0xad, 0xe5, 0xd9, 0x56, 0xec, 0x0b, 0xb5, 0x2c, 0xf0, 0x06, 0xca, 0x7c, 0xcf, 0x04,
	0x79, 0xce, 0xd6, 0xa8, 0x76, 0xbf, 0x02, 0xe0, 0x2d, 0xf3, 0xde, 0x33, 0x0d, 0x9f, 0x01, 0x68,
	0x46, 0xf1, 0xf9, 0xcb, 0x47, 0x59, 0x4d, 0x49, 0xaa, 0xd3, 0x18, 0xea, 0xdf, 0x5b, 0xbc, 0x86,
	0xc2, 0xb6, 0xda, 0xfc, 0x8c, 0xe8, 0x41, 0xe0, 0x1d, 0xac, 0x8f, 0xa6, 0x67, 0x16, 0x83, 0x37,
	0x6a, 0xd6, 0x39, 0x52, 0x97, 0xea, 0xa3, 0xe9, 0xe5, 0x8a, 0x9d, 0x51, 0xe5, 0x22, 0xc1, 0x1e,
	0x5a, 0x8a, 0xc9, 0x1b, 0x59, 0xb0, 0xb5, 0x2c, 0x72, 0x75, 0x4d, 0x91, 0x64, 0x39, 0x54, 0xcf,
	0x73, 0x5d, 0xf2, 0x8f, 0x3d, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x88, 0x50, 0x0a, 0x6b, 0x4c,
	0x01, 0x00, 0x00,
}
